apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dask-notebook-manage-pods
  namespace: dask-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-pods
subjects:
  - kind: ServiceAccount
    name: dask-notebook-sa
    namespace: dask-user
